export * from "./Navbar";
export * from "./Hero";
export * from "./Privacy";
export * from "./GoodStuff";
export * from "./BeautifullyCrafted";
export * from "./BasicsCovered";
export * from "./Theming";
export * from "./CTA";
export * from "./Footer";
